{% set name = "nccmp" %}
{% set version = "1.8.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/remikz/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: a864c4724200d005bf8bc925da717ef7c69b0b0a14730c09540e5a86daad8988

build:
  number: 0
  # Need to skip win because curl needs vc=9 and hdf5 needs vc>=14
  skip: true  # [win]

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - curl
    - libcurl
    - hdf5
    - libnetcdf
  run:
    - curl
    - libcurl
    - hdf5
    - libnetcdf

test:
  commands:
    - test -f $PREFIX/bin/nccmp  # [unix]
    - nccmp --usage

about:
  home: https://gitlab.com/remikz/nccmp
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Comparison of NetCDF files

  description: |
    nccmp compares two NetCDF files bitwise, semantically or with a
    user defined tolerance (absolute or relative percentage). Parallel
    comparisons are done in local memory without requiring temporary
    files. Highly recommended for regression testing scientific models
    or datasets in a test-driven development environment.
  doc_url: https://gitlab.com/remikz/nccmp/-/blob/master/README.md
  dev_url: https://gitlab.com/remikz/nccmp

extra:
  recipe-maintainers:
    - zklaus
